name: Update India News

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script to fetch news
      run: python scripts/fetch_news.py
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

    - name: Commit and push
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add static/data/news.json
        git commit -m "📡 News Update $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"
        git push
